name: Manual Rollback

on:
  workflow_dispatch:

jobs:
  rollback-disabled:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback disabled
        run: echo "Docker rollback is disabled for now."
